### PR TITLE
Add TypeScript type definitions

### PR DESCRIPTION
**Pull request by johnmerchant**
Greetings, I have created some TypeScript type definitions for this package.

### CODE REVIEW

**Comment by hamidjafari** [comment]
hey @jmercha 
thanks for your nice work
just a tiny change:
make `options` in `useSnackbar` optional
`
useSnackbar: (options?: SnackbarOptions)
`
hope maintainer merge this PR.

**Comment by jmercha** [comment]
Done

**Comment by Allianzcortex** [comment]
@evandromacedo @jmercha adding support for ts is really such a fancy feature , however I still cannot install it via commands like `npm i --save-dev @types/react-simple-snackbar` , must add `.d.ts` file manually. would u mind if I creating a PR to add types in https://github.com/DefinitelyTyped/DefinitelyTyped ?

**Comment by evandromacedo** [comment]
I don't mind @Allianzcortex, actually it will help us. Thanks for the support :)

**Comment by Allianzcortex** [comment]
Hi @evandromacedo after checking it again it seems like @types prefer repo owner to [bundle the declared files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package).  After checking it again here is what I meet 👍 

1.  use `import { useSnackbar } from "react-simple-snackbar";` in a `tsx` file , it will show the error : 

image

2. fix is to copy the `types.d.ts` file in the source folder

3. The interesting thing is in `package.json` file , we have defined the types binding : `  "types": "./types.d.ts",`  but `types.d.ts` file is not in published package, so this problem can also be solved if we copy `types.d.ts` file into `node_modules/react-simple-bar`.

4. So could you check the published package to see if `types.d.ts` file is included ? 😄 this is what I get with `npm pack` command : 
image

**Pull request merged**
